[package]
authors = ["Sojan James <sojan.james@gmail.com>"]
name = "threadx-app"
edition = "2024"
version = "0.1.0"

[lib]
harness = false

# needed for each integration test
[[test]]
name = "integration"
harness = false


[dependencies]
board = { workspace = true }
cortex-m = { workspace = true }
cortex-m-rt = { workspace = true }
defmt = { workspace = true }
defmt-rtt = { workspace = true }
panic-probe = { workspace = true }
cortex-m-semihosting = { workspace = true }
threadx-sys = { workspace = true }
netx-sys = { workspace = true }
threadx-rs = { workspace = true }
stm32f4xx-hal = { workspace = true }
static_cell = { workspace = true }
uuid = { workspace = true }
embedded-nal = "0.9.0"
# Use the ringbuffer implementation
ringbuffer = { version = "0.16.0", default-features = false }
embedded-graphics = "0.8.2"
heapless = "0.9.1"
prost = { version = "0.14.1", default-features = false, features = ["derive"] }
prost-types = { version = "0.14.1", default-features = false }
trait-variant = "0.1.2"

log-to-defmt = { version = "0.1.0", optional = true }
minimq = { version = "0.10.0" }

[dev-dependencies]
defmt-test = { workspace = true }

[features]
mqtt_logging = ["dep:log-to-defmt", "minimq/logging"]

