[workspace]
resolver = "3"
members = [
  "app",
  "board",
  "target-tests",
]

# Common dependencies for all target builds

[workspace.dependencies]
board = { path = "board" }
cortex-m = { version = "0.7.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.5"
defmt = "1.0"
defmt-rtt = "1.0"
panic-probe = { version = "1.0", features = ["print-defmt"] }
defmt-test = "0.5"
cortex-m-semihosting = "0.6.0"
threadx-sys = { path = "../../threadx-sys"}
netx-sys = { path = "../../netx-sys"}
threadx-rs = { path = "../../threadx-rs"}
stm32f4xx-hal = { version = "0.23.0", features = ["stm32f412"] }
uuid = {version = "1.18", default-features = false}
static_cell = "2.1.1"
# cargo build/run
[profile.dev]
codegen-units = 1
debug = 2
debug-assertions = true # <-
incremental = false
opt-level = 'z'         # <-
overflow-checks = true  # <-

# cargo test
[profile.test]
codegen-units = 1
debug = 2
debug-assertions = true # <-
incremental = false
opt-level = 3           # <-
overflow-checks = true  # <-

# cargo build/run --release
[profile.release]
codegen-units = 1
debug = 2
debug-assertions = false # <-
incremental = false
lto = 'fat'
opt-level = 3            # <-
overflow-checks = false  # <-

# cargo test --release
[profile.bench]
codegen-units = 1
debug = 2
debug-assertions = false # <-
incremental = false
lto = 'fat'
opt-level = 3            # <-
overflow-checks = false  # <-

