[package]
name = "target-tests"
version = "0.1.0"
edition = "2024"
publish = false

[[test]]
name = "stm32f103"
harness = false

[dev-dependencies]
board = { workspace = true }

[dependencies]
board = { workspace = true }
cortex-m = { workspace = true }
cortex-m-rt = { workspace = true }
defmt = { workspace = true }
defmt-rtt = { workspace = true }
panic-probe = { workspace = true }
cortex-m-semihosting = { workspace = true }
threadx-sys = { workspace = true }
threadx-rs = { workspace = true }
defmt-test = { workspace = true }

[dependencies.stm32f1xx-hal]
version = "0.11.0"
features = ["stm32f103", "medium"]

# [features]
# default = ['defmt-trace']
# # these features are required by defmt
# defmt-default = []
# defmt-trace = []
# defmt-debug = []
# defmt-info = []
# defmt-warn = []
# defmt-error = []
